# Generated by Django 3.2.7 on 2022-01-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newschema',
            name='column_separator',
            field=models.CharField(default=1, max_length=264),
        ),
        migrations.AlterField(
            model_name='newschema',
            name='name',
            field=models.CharField(default=1, max_length=264),
        ),
        migrations.AlterField(
            model_name='newschema',
            name='string_character',
            field=models.CharField(default=1, max_length=264),
        ),
    ]
