# Generated by Django 3.2.7 on 2022-01-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_alter_newschema_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newschema',
            name='column_separator',
            field=models.CharField(default=';', max_length=264),
        ),
        migrations.AlterField(
            model_name='newschema',
            name='string_character',
            field=models.CharField(default='enter string', max_length=264),
        ),
    ]
