# Generated by Django 3.2.9 on 2022-01-04 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0005_auto_20220103_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompleteSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=264)),
                ('main_schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.schemacolumns')),
            ],
        ),
    ]
